MODULE R_interfaces
  USE ISO_C_BINDING, ONLY: C_INT, C_DOUBLE
  INTERFACE
    SUBROUTINE DBLEPR(S, N, V, NV)
      CHARACTER(KIND=1, LEN=*), INTENT(IN) :: S
      INTEGER(C_INT), VALUE :: N
      REAL(C_DOUBLE), INTENT(IN) :: V(*)
      INTEGER(C_INT), VALUE :: NV
    END SUBROUTINE DBLEPR
  END INTERFACE
END MODULE R_interfaces